### ISSUE TITLE
Compatibility with Angular 17+ (standalone) & @jsverse/transloco

### ISSUE THREAD

**Issue by anton-kirschhock** [penleychan/ngx-transloco-router#16]
Seems that there is no support for the new npm naming of the Transloco package.

Is this something you plan to do?

**Comment by penleychan** [comment]
Sorry, I do not have any plans to migrate/support newer angular/transloco packages. 

This was originally port for a client that was using transloco with prefix route requirements and I just extracted it out to make it useable. Since I am no longer working with that client/project I don't see myself spending time on this.

Feel free to fork and make adjustments.
