### ISSUE TITLE
Subroutes

### ISSUE THREAD

**Issue by radim-kliment** [penleychan/ngx-transloco-router#8]
Is this library working with sub-routes?
I have modules and submodules with routing and translation not woring on second level of routes 
domain.com/en/registration <- working
domain.com/en/registration/step-one <- not-working

**Comment by penleychan** [comment]
Make sure you register the module.     LocalizeRouterModule.forChild(routes). Refer to the demo app

**Comment by radim-kliment** [comment]
Yes Iam calling LocalizeRouterModule.forChild(routes):

I have:
- lazy loaded module (register in root) with lazy loaded children routes (with routing modules). Iam calling LocalizeRouterModule.forChild(routes) on lazy loaded module and in children modules. Translation of names working, but Iam getting "Error: NG04002: Cannot match any routes" on second defined language on lazy loaded subroutes (ex.: domain.com/en/registration/step-one).

**Comment by penleychan** [comment]
Since most of my production projects is running on ng13 I don't see the issue.

I created angular 14 version to test. Looks like something changed in angular 14 routing, seems like it is duplicating routes when changing language.
Without you sharing the whole error, my assumption is that it is attempting to navigate to 
`/en/registration/step-one/registration/step-one`

Can you confirm if that's what's happening?

**Comment by radim-kliment** [comment]
It looks like it doesnt translate the route, because this routes working:

/en/registration/step-one
/cs/registrace/step-one

but not this desired translated one:
/cs/registrace/krok-jedna

**Comment by penleychan** [comment]
Hello,

Can you try the latest version.
I've changed the version to 14.0.0 to match with angular versioning.

`npm i @penleychan/ngx-transloco-router@14.0.0`

I've also updated the demo app to somewhat similar to [@gilsdav/ngx-translate-router](https://github.com/gilsdav/ngx-translate-router)

Regards

**Comment by radim-kliment** [comment]
Thanks, now it's working with latest version.
